### PR TITLE
forms validation using regex

### PR DESCRIPTION
**Pull request by winner-winifredd**
#Attached regex to all input fields

### CODE REVIEW

**Comment by emmirays** [comment]
Hello winner,
I really admire your code, please could you just put me through?

**Review by Promtech1 — APPROVED** [review]
Nice one miss winner

**Comment by stackmaestro-dev** [comment]
> Hello winner, I really admire your code, please could you just put me through?

of course, i don't mind.

**Comment by emmirays** [comment]
> > Hello winner, I really admire your code, please could you just put me through?
> 
> of course, i don't mind.

> > Great!

**Pull request merged**
